"""contacts and device sharing

Revision ID: 50f994790074
Revises: 3f6816c61421
Create Date: 2026-09-26 11:24:15.058118
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import via.db.base

revision: str = "50f994790074"
down_revision: str | None = "3f6816c61421"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("requester_id", sa.String(length=26), nullable=False),
        sa.Column("addressee_id", sa.String(length=26), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("created_at", via.db.base.UTCDateTime(), nullable=False),
        sa.Column("accepted_at", via.db.base.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["addressee_id"],
            ["users.id"],
            name=op.f("fk_contacts_addressee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
            name=op.f("fk_contacts_requester_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint("requester_id", "addressee_id", name=op.f("uq_contacts_requester_id")),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contacts_addressee_id"), ["addressee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contacts_requester_id"), ["requester_id"], unique=False
        )

    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("accepts_shares", sa.Boolean(), server_default=sa.text("1"), nullable=False)
        )

    # ### end Alembic commands ###
    # Only phones and desktops accept shares by default.
    op.execute(
        "UPDATE devices SET accepts_shares = 0 WHERE type NOT IN ('android', 'ios', 'desktop')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_column("accepts_shares")

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contacts_requester_id"))
        batch_op.drop_index(batch_op.f("ix_contacts_addressee_id"))

    op.drop_table("contacts")
    # ### end Alembic commands ###
