"""initial schema

Revision ID: 3f6816c61421
Revises:
Create Date: 2026-09-26 03:13:38.311993
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import via.db.base

revision: str = "3f6816c61421"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", via.db.base.UTCDateTime(), nullable=False),
        sa.Column("disabled_at", via.db.base.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "app_tokens",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes", sa.String(length=255), nullable=False),
        sa.Column("created_at", via.db.base.UTCDateTime(), nullable=False),
        sa.Column("last_used_at", via.db.base.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_app_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_app_tokens_token_hash")),
    )
    with op.batch_alter_table("app_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_app_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "devices",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", via.db.base.UTCDateTime(), nullable=False),
        sa.Column("last_seen_at", via.db.base.UTCDateTime(), nullable=True),
        sa.Column("push_provider", sa.String(length=16), nullable=False),
        sa.Column("push_target", sa.LargeBinary(), nullable=True),
        sa.Column("revoked_at", via.db.base.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_devices_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_devices_token_hash")),
    )
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_devices_user_id"), ["user_id"], unique=False)

    op.create_table(
        "invites",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=26), nullable=True),
        sa.Column("created_at", via.db.base.UTCDateTime(), nullable=False),
        sa.Column("expires_at", via.db.base.UTCDateTime(), nullable=False),
        sa.Column("used_by", sa.String(length=26), nullable=True),
        sa.Column("used_at", via.db.base.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_invites_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["used_by"], ["users.id"], name=op.f("fk_invites_used_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invites")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_invites_code_hash")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", via.db.base.UTCDateTime(), nullable=False),
        sa.Column("last_used_at", via.db.base.UTCDateTime(), nullable=False),
        sa.Column("expires_at", via.db.base.UTCDateTime(), nullable=False),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "pushes",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("source_device_id", sa.String(length=26), nullable=True),
        sa.Column("source_app_token_id", sa.String(length=26), nullable=True),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("encryption", sa.String(length=16), nullable=False),
        sa.Column("key_id", sa.String(length=16), nullable=True),
        sa.Column("wrapped_key", sa.LargeBinary(), nullable=True),
        sa.Column("meta", sa.LargeBinary(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_stored", sa.Boolean(), nullable=False),
        sa.Column("created_at", via.db.base.UTCDateTime(), nullable=False),
        sa.Column("expires_at", via.db.base.UTCDateTime(), nullable=False),
        sa.Column("purged_at", via.db.base.UTCDateTime(), nullable=True),
        sa.Column("history_until", via.db.base.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_app_token_id"],
            ["app_tokens.id"],
            name=op.f("fk_pushes_source_app_token_id_app_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_device_id"],
            ["devices.id"],
            name=op.f("fk_pushes_source_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_pushes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pushes")),
    )
    with op.batch_alter_table("pushes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pushes_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_pushes_source_device_id"), ["source_device_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_pushes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "deliveries",
        sa.Column("push_id", sa.String(length=26), nullable=False),
        sa.Column("device_id", sa.String(length=26), nullable=False),
        sa.Column("state", sa.String(length=12), nullable=False),
        sa.Column("delivered_at", via.db.base.UTCDateTime(), nullable=True),
        sa.Column("acked_at", via.db.base.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_deliveries_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["push_id"],
            ["pushes.id"],
            name=op.f("fk_deliveries_push_id_pushes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("push_id", "device_id", name=op.f("pk_deliveries")),
    )
    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.create_index("ix_deliveries_device_state", ["device_id", "state"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.drop_index("ix_deliveries_device_state")

    op.drop_table("deliveries")
    with op.batch_alter_table("pushes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pushes_user_id"))
        batch_op.drop_index(batch_op.f("ix_pushes_source_device_id"))
        batch_op.drop_index(batch_op.f("ix_pushes_expires_at"))

    op.drop_table("pushes")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))

    op.drop_table("sessions")
    op.drop_table("invites")
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_devices_user_id"))

    op.drop_table("devices")
    with op.batch_alter_table("app_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_app_tokens_user_id"))

    op.drop_table("app_tokens")
    op.drop_table("users")
    # ### end Alembic commands ###
